import type { AnalysisResult } from './analyzer';

export async function exportAnalysisPDF(result: AnalysisResult, currency: string) {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { jsPDF } = await import(/* webpackIgnore: true */ 'jspdf');
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Helper to add text with word wrap
  function addText(text: string, x: number, fontSize: number, color: [number,number,number] = [17,24,39], maxWidth?: number) {
    doc.setFontSize(fontSize);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth || pageWidth - 2*x);
    doc.text(lines, x, y);
    y += lines.length * fontSize * 0.5 + 4;
    if (y > 270) { doc.addPage(); y = 20; }
  }

  // Title
  doc.setFontSize(24);
  doc.setTextColor(79, 70, 229); // indigo
  doc.text('DEALWISE', 20, y);
  y += 10;
  addText('Contract Analysis Report', 20, 16, [75, 85, 99]);
  addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 20, 10, [156, 163, 175]);
  y += 10;

  // Score + Rate
  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;
  addText(`Deal Score: ${result.overallScore}/100`, 20, 18, result.overallScore >= 70 ? [5,150,105] : result.overallScore >= 40 ? [217,119,6] : [220,38,38]);
  addText(`Recommendation: ${result.recommendation.toUpperCase().replace('_', ' ')}`, 20, 14);
  addText(`Nominal Rate: ${currency} ${result.nominalHourlyRate.toFixed(2)}/hr`, 20, 12);
  addText(`Effective Rate: ${currency} ${result.effectiveHourlyRate.toFixed(2)}/hr`, 20, 12, result.rateReduction > 20 ? [220,38,38] : [17,24,39]);
  addText(`Rate Reduction: ${result.rateReduction.toFixed(1)}%`, 20, 12);
  y += 5;

  // Red Flags
  if (result.redFlags.length > 0) {
    doc.line(20, y, pageWidth - 20, y); y += 8;
    addText(`RED FLAGS (${result.redFlags.length})`, 20, 14, [220, 38, 38]);
    result.redFlags.forEach((flag, i) => {
      addText(`${i+1}. [${flag.severity.toUpperCase()}] ${flag.issue}`, 24, 11, [17,24,39]);
      if (flag.impact) addText(`   Impact: ${flag.impact}`, 28, 9, [75,85,99]);
      if (flag.suggestion) addText(`   Suggestion: ${flag.suggestion}`, 28, 9, [5,150,105]);
      y += 2;
    });
  }

  // Missing Clauses
  if (result.missingClauses.length > 0) {
    doc.line(20, y, pageWidth - 20, y); y += 8;
    addText(`MISSING PROTECTIONS (${result.missingClauses.length})`, 20, 14, [234, 88, 12]);
    result.missingClauses.forEach((mc, i) => {
      addText(`${i+1}. [${mc.importance.toUpperCase()}] ${mc.name}`, 24, 11);
      addText(`   ${mc.description}`, 28, 9, [75,85,99]);
      if (mc.suggestedLanguage) addText(`   Add: ${mc.suggestedLanguage}`, 28, 9, [5,150,105]);
      y += 2;
    });
  }

  // Green Flags
  if (result.greenFlags.length > 0) {
    doc.line(20, y, pageWidth - 20, y); y += 8;
    addText(`POSITIVE CLAUSES (${result.greenFlags.length})`, 20, 14, [5, 150, 105]);
    result.greenFlags.forEach((gf, i) => {
      addText(`${i+1}. ${gf.benefit}`, 24, 10, [17,24,39]);
    });
  }

  // Summary
  if (result.summary) {
    y += 5;
    doc.line(20, y, pageWidth - 20, y); y += 8;
    addText('SUMMARY', 20, 14, [79, 70, 229]);
    addText(result.summary, 20, 10, [75, 85, 99], pageWidth - 40);
  }

  // AI Insights
  if (result.aiInsights) {
    y += 5;
    addText('AI INSIGHTS', 20, 14, [79, 70, 229]);
    addText(result.aiInsights, 20, 10, [75, 85, 99], pageWidth - 40);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by DEALWISE — dealwise.app', 20, 285);

  doc.save('dealwise-analysis-report.pdf');
}
