import type { AnalysisResult } from "./analyzer";

export function exportAnalysisDOCX(result: AnalysisResult, currency: string) {
  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="utf-8"><title>DealWise Analysis Report</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #333; margin: 40px; }
  h1 { color: #4F46E5; font-size: 24pt; border-bottom: 2px solid #4F46E5; padding-bottom: 8px; }
  h2 { color: #111827; font-size: 16pt; margin-top: 24px; border-bottom: 1px solid #E5E7EB; padding-bottom: 4px; }
  h3 { color: #4B5563; font-size: 13pt; }
  .score { font-size: 36pt; font-weight: bold; color: ${result.overallScore >= 70 ? '#059669' : result.overallScore >= 40 ? '#D97706' : '#DC2626'}; }
  .recommendation { display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 12pt;
    background: ${result.recommendation === 'sign' ? '#ECFDF5' : result.recommendation === 'negotiate' ? '#FFFBEB' : '#FEF2F2'};
    color: ${result.recommendation === 'sign' ? '#059669' : result.recommendation === 'negotiate' ? '#D97706' : '#DC2626'}; }
  .flag { margin: 8px 0; padding: 8px 12px; border-left: 3px solid; background: #F9FAFB; }
  .flag.critical { border-color: #DC2626; }
  .flag.high { border-color: #EA580C; }
  .flag.medium { border-color: #D97706; }
  .flag.low { border-color: #2563EB; }
  .green { border-left: 3px solid #059669; padding: 8px 12px; margin: 8px 0; background: #ECFDF5; }
  .suggestion { background: #ECFDF5; padding: 8px 12px; margin: 4px 0 12px 0; border: 1px solid #A7F3D0; font-size: 10pt; }
  table { border-collapse: collapse; width: 100%; margin: 8px 0; }
  td, th { border: 1px solid #E5E7EB; padding: 6px 10px; text-align: left; font-size: 10pt; }
  th { background: #F3F4F6; font-weight: bold; }
  .meta { color: #9CA3AF; font-size: 9pt; }
</style></head>
<body>
<h1>dealwise Analysis Report</h1>
<p class="meta">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

<h2>Deal Score</h2>
<p class="score">${result.overallScore}/100</p>
<p class="recommendation">${result.recommendation.toUpperCase().replace('_', ' ')}</p>

<h2>Rate Analysis</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Quoted Rate</td><td>${currency} ${result.nominalHourlyRate.toFixed(2)}/hr</td></tr>
<tr><td>Effective Rate</td><td>${currency} ${result.effectiveHourlyRate.toFixed(2)}/hr</td></tr>
<tr><td>Rate Reduction</td><td>${result.rateReduction.toFixed(1)}%</td></tr>
${result.contractType ? `<tr><td>Contract Type</td><td>${result.contractType}</td></tr>` : ''}
</table>

<h2>Red Flags (${result.redFlags.length})</h2>
${result.redFlags.map(f => `
<div class="flag ${f.severity}">
<h3>[${f.severity.toUpperCase()}] ${f.issue}</h3>
<p>${f.impact}</p>
${f.suggestion ? `<div class="suggestion"><strong>Counter-proposal:</strong> ${f.suggestion}</div>` : ''}
</div>`).join('')}

<h2>Missing Protections (${result.missingClauses.length})</h2>
${result.missingClauses.map(m => `
<div class="flag ${m.importance === 'critical' ? 'critical' : m.importance === 'important' ? 'medium' : 'low'}">
<h3>[${m.importance.toUpperCase()}] ${m.name}</h3>
<p>${m.description}</p>
${m.suggestedLanguage ? `<div class="suggestion"><strong>Add this language:</strong> ${m.suggestedLanguage}</div>` : ''}
</div>`).join('')}

<h2>Positive Clauses (${result.greenFlags.length})</h2>
${result.greenFlags.map(g => `<div class="green"><p>${g.benefit}</p></div>`).join('')}

<h2>Summary</h2>
<p>${result.summary}</p>

${result.aiInsights ? `<h2>AI Analysis</h2><p>${result.aiInsights}</p>` : ''}

<hr>
<p class="meta">This report was generated by dealwise (dealwise.app). It is not legal advice.</p>
</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'dealwise-report.doc';
  a.click();
  URL.revokeObjectURL(url);
}
